### ISSUE TITLE
Unsupported interface type: Decrypt Mirror

### ISSUE THREAD

**Issue by msanchezt** [PaloAltoNetworks-BD/pan-configurator#10]
Hi!
Recently we configured a new type of interface in our Firewall (interface type: "Decrypt Mirror"). 
And seems that this type of interface is not supported, is that right?

* ** ERROR ** * unsupported ethernet interface type : not found
XML line #65535, XPATH: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='DD3FW']/config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet/entry[@name='ethernet1/21']
<entry name="ethernet1/21">
 <link-duplex>auto</link-duplex>
 <comment>Decrypt SSL Mirroring</comment>
 <decrypt-mirror/>
</entry>

The error shows when loading the XML file, right here:

        $panc = new PanoramaConf ();
        $panc->load_from_file ( $origfile );

**Comment by cpainchaud** [comment]
can you please forward the full error message (unless this is all of it ?)

decrypt mirror might be missing, but i can add it fast

**Comment by msanchezt** [comment]
Hi, this is the full error message, thanks:

* ** ERROR ** * unsupported ethernet interface type : not found
XML line #65535, XPATH: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='CD1FW']/config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet/entry[@name='ethernet1/24']
<entry name="ethernet1/24">
 <link-duplex>auto</link-duplex>
 <comment>Decrypt SSL Mirroring</comment>
 <decrypt-mirror/>
</entry>


 *** Backtrace ***
0 ****
1 ****
2 ****
3 ****
4 ****
5 ****
6 ****
7 ****
8 ****
9 ****
       ::pan-configurator-master/lib/network-classes/class-EthernetInterface.php line 97
   PanoramaConf: / Template:CD1FW / PANConf: / EthernetIfStore:EthernetIfaces / EthernetInterface:ethernet1/24
       EthernetInterface::load_from_domxml() @
           pan-configurator-master/lib/object-classes/class-ObjStore.php line 244
   PanoramaConf: / Template:CD1FW / PANConf: / EthernetIfStore:EthernetIfaces
       ObjStore::load_from_domxml() @
           pan-configurator-master/lib/network-classes/class-EthernetIfStore.php line 69
   PanoramaConf: / Template:CD1FW / PANConf: / EthernetIfStore:EthernetIfaces
       EthernetIfStore::load_from_domxml() @
           pan-configurator-master/lib/network-classes/class-NetworkPropertiesContainer.php line 71
   PanoramaConf: / Template:CD1FW / PANConf: / NetworkPropertiesContainer
       NetworkPropertiesContainer::load_from_domxml() @
           pan-configurator-master/lib/device-and-system-classes/class-PANConf.php line 230
   PanoramaConf: / Template:CD1FW / PANConf:
       PANConf::load_from_domxml() @
           pan-configurator-master/lib/device-and-system-classes/class-Template.php line 49
   PanoramaConf: / Template:CD1FW
       Template::load_from_domxml() @
           pan-configurator-master/lib/device-and-system-classes/class-PanoramaConf.php line 266
   PanoramaConf:
       PanoramaConf::load_from_domxml() @
           pan-configurator-master/lib/device-and-system-classes/class-PanoramaConf.php line 126
   PanoramaConf:
       PanoramaConf::load_from_xmlstring() @
           pan-configurator-master/lib/device-and-system-classes/class-PanoramaConf.php line 468
   PanoramaConf:
       PanoramaConf::load_from_file() @
           scriptBase.php line 504

**Comment by cpainchaud** [comment]
thx, should be ok with commit I just made. please test and tell me.

**Comment by msanchezt** [comment]
Tested and working.

Thanks!

**Comment by cpainchaud** [comment]
great

have a nice day
