### ISSUE TITLE
A tool to extract all rules matching a host (Address Groups included, and multi VSYS)?

### ISSUE THREAD

**Issue by msanchezt** [PaloAltoNetworks-BD/pan-configurator#2]
Hi,

I was wondering if there is any way to "extract" all the rules from XML snapshot that matches a HOST.

I mean, exporting the XML and searching, for example, the rules that matches the host "10.142.16.2/32" is easy, but with the Address Groups involved... that can become a hard task.

Also, any way that handle multi VSYS configurations?

Thak you very muchfor the effort.

**Comment by cpainchaud** [comment]
Hi,

 This library is multi-vsys and device-group aware. What you describe is perfectly doable within a custom script using my library (example-xxxx.php scripts shows you the basic skeletons of a script).

 Also note that the utility utils/rules-edit.php cannot 'export xml' but can filter rules on almost any parameter (included network matches) and you can then tag, delete, disable/whatever action is supported.

**Comment by msanchezt** [comment]
I've been trying with that and I'm getting this error:

* ** ERROR  ** *   xml  element <vsys> was not found

With the example .XML is working finee, the error is when using my own .XML.

This is the part of your XML (I guess) is used  to locate the "vsys1":

<settings>
            <multi-vsys>no</multi-vsys>
            <operational-mode>normal</operational-mode>
            <vpn-disable-mode>no</vpn-disable-mode>
          </settings>
          <config>
            <devices>
              <entry name="localhost.localdomain">
                <vsys>
                  <entry name="vsys1"/>
                </vsys>
              </entry>
            </devices>
          </config>



And  this is the part of my XML used to locate  "vsys1":


 <entry name="NAMEOFMYVSYS">
          <devices>
            <entry name="0004C10341">
              <vsys>
                <entry name="vsys1"/>
              </vsys>
            </entry>
            <entry name="0004C101238">
              <vsys>
                <entry name="vsys1"/>
              </vsys>
            </entry>
            <entry name="0004C212477">
              <vsys>
                <entry name="vsys1"/>
              </vsys>
            </entry>
            <entry name="0004C234178">
              <vsys>
                <entry name="vsys1"/>
              </vsys>
            </entry>
          </devices>


As you can see, both are quite  different, so, you know where the error can be?
(I can't past you  my entire <entry name ="WHATEVERNAME"> </entry> because is  300.000 lines long!

Thanks again,

**Comment by cpainchaud** [comment]
You're mixing Panorama templates and PANOS vsys I think.

My scripts work on full configs of the product, not parts of them. Just load the whole config (Panorama or PANOS/Firewall) into the scripts.

**Comment by msanchezt** [comment]
Hi,

This is just what I'm doing here. I make an snapshot of the Panorama
configuration, then an export and this is the .XML file I pass to the
script.


*Marcel Sánchez Toledano*


2015-03-31 18:49 GMT+02:00 Christophe <notifications@github.com>:

**Comment by cpainchaud** [comment]
what is the full error message ?

**Comment by msanchezt** [comment]
This is the full  error message:

![image](https://cloud.githubusercontent.com/assets/6965401/6935591/34d94adc-d848-11e4-8c8f-a9b9c8e64af8.png)


Thanks,

**Comment by cpainchaud** [comment]
You are trying to load a Panorama configuration with a PANConf object that is meant to be used for Firewall configs.

Please use PanoramaConf object instead.

**Comment by msanchezt** [comment]
Hi again,

My mistake, working as expected now with PanoramaConf.

With Addresses and Services is working perfectly fine, but  I'm having problems dealing with Rules:

    $countGroups2 = $sub->addressStore->count();

    $countGroups3 = $sub->serviceStore->count();

    $countGroups4 = $sub->ruleStore->count();    

* * ERROR * * Died on user notice or warning!! Error: Undefined property: DeviceGroup::$ruleStore

**Comment by cpainchaud** [comment]
rules are in a different store for each time:

rule->securityRules    
rule->natRules
rule->decryptionRules

all of them are RuleStore class.

please have a look at the /doc/index.html to find variables and their class names. Also example-basics-panos.php should help you to get a picture of the different places to look at.

**Comment by msanchezt** [comment]
Hi, following your advice I've been able to run my tests. But I have one doubt, with: ServiceRuleContainer class. I cant find any example using that class! Maybe you can help me with that..

Actually, what I need to use is a particular method: hasObjectRecursive( $my_address ). If I pass and Address name, will this method find a Rule which have an Address Group (and that Address Group contains this Address).

**Comment by msanchezt** [comment]
Hi,

I've been able to run some tests with your help. But I have the following problem:

I have all the AddressGroups in an array. Can I use a foreach to iterate all this AddressGroups and check if any of this has (as Source or Destination) an Address?

$object = "NAME_10.12.10.123";

$adressGroup->hasObjectRecursive( Address|AddressGroup $object )

This will look inside every AddressGroup? Looking for Addresses?

Can't find any example with hasObjectRecursive.

Thanks!

**Comment by cpainchaud** [comment]
yes, do a foreach loop for each object you want to test.

this function is 'recursive' because it will look inside the rule's groups
if object is there (and inside the groups of the groups ... it's nested).

but be careful, it doesn't look 'inside' an AddressGroup you provide as an
argument, it is not the purpose. It looks inside groups that are part of
the AddressRuleContainer.

**Comment by msanchezt** [comment]
Sorry, I see the first part of your answer, but not the second part...

What I'm doing is iterating an array with all the AddressGroups to find which ones contains a certain Address. Then, I will iterate each Rule to find which rules contains this Address or Addresses Groups. That way I can make an export of all the rules related with, for example, a host in particular.

But you are talking about "AddressRuleContainer", actually I don't really understand what is the exact purpose of this class. Any example where it's used? Can you give me a brief explanation about it? Because maybe this class could save me some time and some lines of code!

**Comment by cpainchaud** [comment]
AddressRuleContainer is used by rules to manage source and destination
objects.

you can access them from $rule->source and $rule->destination

in fact all my example-xxx script are using them as you can see :)

anyway, let's imagine your scenario where you are looking for SecurityRules
using an object, you have 3 or 4 ways to do what you are looking for:

version 1 : use rule filter

$objectNameToLookFor = 'server2';
$objectionLocation = 'device-group1';
$panoramaFile = 'config.xml';

$panorama = new PanoramaConf();
$panorama->load_from_file($panoramaFile);
$deviceGroup = $panorama->findDeviceGroup($objectLocation);

// the following will select all rules from device group matching a
specific query
$rules = $deviceGroup->securityRule->rules("(from has.recursive
{$objectNameToLookFor}) or (to has.recursive {$objectNameToLookFor})" );

// now do your you want with the rules:
foreach( $rules as $rule )
{
   // do something with $rule here
}

version 2 : do filtering by yourself in the code, dont use filter

$objectNameToLookFor = 'server2';
$objectionLocation = 'device-group1';
$panoramaFile = 'config.xml';

$panorama = new PanoramaConf();
$panorama->load_from_file($panoramaFile);

// look for specific device group
$deviceGroup = $panorama->findDeviceGroup($objectLocation);

// look for specific object
$object = $deviceGroup->addressStore->find($objectNameToLookFor);
if( $object === null )
  die("ERROR : object '$objectNameToLookFor' not found \n");

$rules = $deviceGroup->securityRule->rules( );

foreach( $rules as $rule )
{

if( $rule->source->hasObjectRecursive($object) ||
    $rule->destination->hasObjectRecursive($object) )
{
     /// do something with $rule here
}

}
