### ISSUE TITLE
Extract all Applications

### ISSUE THREAD

**Issue by msanchezt** [PaloAltoNetworks-BD/pan-configurator#3]
Hi,

I need to print to a file all the Applications available in Panorama (not all the different Applications used in the Policy! I nned all the Applications or Custom Applications available).

So my question is: there is any utility that alredy do that? In case there isn't, can you propose or detail the best way to acomplish that? (I alredy have a script which loads all the VSYS in Panorama and process it).

**Comment by cpainchaud** [comment]
as of today with my lib you will be missing a things:
1 - my lib loads a cached version of PAN Application database so it's available even when you work on offline files. It is using file object-class/predefined.xml which is refreshed once in a while manually by me. There could be improvments by load application database live from API but I found it to be stressing for the management CPU of firewalls.
2 - this lib doesn't read local (shared, vsys, device-group level) applications. I simply didn't find time/need for that. Whenever I find an application I i don't know in policies, I create it as a "temp' application record.

as of today, I think the best way for you is to read Xml directly (remember that my lib offers root DOM Element of any object : $object->xmlroot . you can also use it to do an API call to get predefined database app if needed.

**Comment by msanchezt** [comment]
I think option 1 would be the best option,

Any array, function or something in your API I can use to iterate and print all the Applications names on this file? Or do I need to parse this file?
Thanks  again,

**Comment by cpainchaud** [comment]
These are not options, read carefuly, I am saying my lib has 2 limitations that means you can't do it natively for custom applications.

For official applications please have a look at PANConf->appStore and its associated documentation for class AppStore
