### ISSUE TITLE
Error with rule-merger

### ISSUE THREAD

**Issue by msanchezt** [PaloAltoNetworks-BD/pan-configurator#4]
Hi,

I have this error with the rule-merger utility, it's only happening with the method "matchFromToSrcDstApp", all the other methods are working fine:

php  pan-configurator-master/utils/rule-merger.php in="MY_INPUT.XML" out=MY_OUTPUT.xml panoramaPreRules method=matchFromToSrcDstApp location=MY_DV_NAME

* ** ERROR ** * You cannot merge 'application-default' type service stores with app-default ones

 *** Backtrace ***
       pan-configurator-master/lib/container-classes/class-ServiceRuleContainer.php line 276
   PanoramaConf: / DeviceGroup:VPN-SMARTPHONES / RuleStore:Security / SecurityRule:50590.1 / ServiceRuleContainer:service
       ServiceRuleContainer::merge() @
           /home/teleco/Marcel/PaloAltoPHP/pan-configurator-master/utils/rule-merger.php line 485
       ::/home/teleco/Marcel/PaloAltoPHP/pan-configurator-master/utils/rule-merger.php line 699

**Comment by cpainchaud** [comment]
Hi,

 I think it should be fixed now. Can you try ?

thx

**Comment by msanchezt** [comment]
Hi,

Is working now, thanks!

**Comment by cpainchaud** [comment]
yw, thx for reporting !
