### ISSUE TITLE
Call to undefined method AddressGroup::value()

### ISSUE THREAD

**Issue by msanchezt** [PaloAltoNetworks-BD/pan-configurator#5]
Hi,

Not exactly sure if it's a problem with the API, I believe could be an Address object created in my Panorama with a bad syntax value, but can't find how to locate the object or how to debug the error.

The error is: 
Fatal error: Call to undefined method AddressGroup::value() in /home/teleco/Marcel/PaloAltoPHP/scriptBase.php on line 322

And the error appears when I'm iterating over all the values of the IP Addresses created on my Panorama. Heere you can see that I'm printing all the values:

10.16.156.0/2410.241.23.0/2410.241.38.0/24192.168.182.0/2410.117.30.0/2410.121.117.0/2410.121.148.0/2410.113.150.0/2410.115.135.0/24
Fatal error: Call to undefined method AddressGroup::value() in /home/teleco/Marcel/PaloAltoPHP/scriptBase.php on line 322

The line which is complaining about in my custom script is this one:

if ($classname = "Address") {

                        if ($o->isTmpAddr ()) {
                                continue;
                        }
                        print $o->value ();   <---- Line 322

**Comment by cpainchaud** [comment]
Hi,

for some reasons, $o seems to be an AddressGroup in your case. I see you are checking if classname == "Address" which is good but I fear you soemwhere in your code there is a race condition and you don"t update classname for each object.

I suggest that you investigate why classname is Address while it should be AddressGroup (means your script logic is wrong somewhere and may lead to more issues) or replace  " if ($classname = "Address") "  by  "    if( !$o->isGroup() )    "

**Comment by msanchezt** [comment]
The " if( !$o->isGroup() ) " has solved the problem, thank you. Anyway, I'll check my code in order to find the real issue. Thanks.
