### ISSUE TITLE
Feature request: Call to add Address to an AddressGroup via API

### ISSUE THREAD

**Issue by rmoesbergen** [PaloAltoNetworks-BD/pan-configurator#6]
I'd like to request a feature: create a call that allows one to add an Address object to an AddressGroup using the API.  So, for example:

$newip = $devgroup->addressStore->api_newAddress('Test Address', 'ip-netmask', '8.8.8.8', 'Test Address');
$adgroup = $devgroup->addressStore->find('TEST ADDRESS GROUP');
$adgroup->API_add($newip)

Would it be possible to add this call?

**Comment by cpainchaud** [comment]
Hi,

 so there was a hidden way to do it with $group->API_sync()
 Anyway I've just committed 2 new functions : API_add() and API_delete() as per your request. Let me know if they work well.

**Comment by rmoesbergen** [comment]
Awesome, thank you!
