### ISSUE TITLE
Extracting routes

### ISSUE THREAD

**Issue by msanchezt** [PaloAltoNetworks-BD/pan-configurator#8]
Hi,

Inside the PA FW you can run the command "show routing route" to know routes in all Virtual Routes (static, ospf,bgp,...). So, I'm trying to extract all this rules from the FIrewall configuration and I'm getting this error:

* ** ERROR ** * Died on user notice or warning!! Error: Use of undefined constant LIBXML_PARSEHUGE - assumed 'LIBXML_PARSEHUGE' on /[MY_OWN_PATH]/pan-configurator-master/lib/device-and-system-classes/class-PANConf.php:122

Any idea about the reason of the error? 

Also, I can't find any examples related with routes. And can't figure out how to deal with routes. I guess something like that?

$panc = new PANConf();
$panc->load_from_file ( $origfile );

But I'm not sure how to obtain the Virtual Routers form here (VirtualRouterStore).

**Comment by cpainchaud** [comment]
Hi,
 Can you please share your version of PHP ?  LIBXML_PARSEHUGE  is a constant that should be defined in PHP loaded with module lib-xml

**Comment by msanchezt** [comment]
That's my version:

PHP Version => 5.5.28
libxml2 Version => 2.6.26

I can load Panorama config files but not PANOS config files.

**Comment by cpainchaud** [comment]
There has to be an issue with your PHP install , if you check here, only old version of PHP are getting this error message :
https://3v4l.org/Qsp0l

is it a version bundled with your Mac OS X? Custom install for windows ?

**Comment by msanchezt** [comment]
I'm not sure I understand If what I'm getting is correct or an error:

Running:
<?php
var_dump(LIBXML_PARSEHUGE);

Outputs:
string(16) "LIBXML_PARSEHUGE"

I'm on a Red Hat.

**Comment by cpainchaud** [comment]
a string ? wow ...

dont you have any update available for your RedHat ? LIBXML_PARSEHUGE is supposed to be an int.

before you load my library you can eventually define this constant manually:
define ( 'LIBXML_PARSEHUGE' , 524288 );

**Comment by cpainchaud** [comment]
also concerning your original request, if you to know the routes installed in the FW at runtim (config hold static routes only) then you need to use API OP type command.

From PanAPIConnector class it looks like:

$connector->sendOpRequest('<show><config><merged/></config></show>');

**Comment by msanchezt** [comment]
I need to get dynamic routes also (OSPF routes, mainly).

Which is the best way to get static and dynamic routes?


*Marcel Sánchez Toledano*


2015-12-17 23:58 GMT+01:00 Christophe <notifications@github.com>:

**Comment by cpainchaud** [comment]
API is the best way for runtime routes.

PanAPIConnector
$connector->sendOpRequest('<show><routing><route/></routing></show>');
