### ISSUE TITLE
Excel output is missing To Field

### ISSUE THREAD

**Issue by mkrajcovic** [PaloAltoNetworks-BD/pan-configurator#9]
I am presently using your latest build with an exported configuration from Palo Alto FW version 7.0. The file I am working with in just a standard running-config.xml. When I use the action=exportToExcel:file.xls
the results provided are missing the To field.

All the rules are processed correctly and the overall counter appears to be correct also, however, when I load the excel file my columns at the top are listed in this order:

![image](https://cloud.githubusercontent.com/assets/12157149/12079597/e673695a-b20c-11e5-8c54-4beffadfc607.png)

Please let me know if there is any further information I can provide and if this is something being resolved as I was really hoping to leverage your tool to parse my rules into an Excel format for easy editing.

**Comment by cpainchaud** [comment]
hi

it should be fixed in latest version

thx for reporting

**Comment by mkrajcovic** [comment]
Thanks for the very prompt followup!! I wanted to confirm that the latest version is working without any issues at all.. Thanks for the great tool and keep up the work! :+1:

**Comment by cpainchaud** [comment]
you are welcome. Cheers

**Comment by mkrajcovic** [comment]
Thanks again Christophe...

I did notice one additional component that is missing from the action for exportToExcell when used with the security rules. Can you tell me if it was intentional that some of the fields that are in the xml are not available - for instance, it seems that 'Source User' is not present nor is the "log option" (the policy used for logging).

If it is just an oversight could you make those fields also available in that function (most importantly for myself would be that Source User option).

Thanks again for all your efforts and keep up the great work!

Mark

________________________________

**Comment by cpainchaud** [comment]
I just made an update for source users and log-profile in excel, can you try it ?

**Comment by mkrajcovic** [comment]
I’d be more than happy too..  Man you are on the ball.. I like when I converse with other dev’s that are prompt like myself. Nothing like seeing that issues are being addressed and the project still has life flowing ;)

I’ll let you know the outcome shortly..  just have to clone the source and test it out.
Thanks again

Mark

**Comment by cpainchaud** [comment]
you're welcome, let me know how that works
